# Generated by Django 4.1.6 on 2023-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memos',
        ),
    ]
