# Generated by Django 4.1.6 on 2023-02-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memos',
        ),
    ]
